name: 'techjavelin/iac-github-actions // terraform // lint'
description: 'Lints your terraform files using tflint'

inputs:
  terraform-dir:
    description: "Absolute path or relative path from project root to where your terraform files are"
    default: '.'
    required: false

  version:
    description: Use a specific version of tflint
    default: latest
    required: false

  config:
    description: Use a specific config file for tflint
    required: false

  format:
    description: Force tflint to output in a different format (overrides config)
    required: false

  vars:
    description: Comma-delimited list of variables
    required: false

outputs:
  vars:
    description: The variables that were passed to tflint
    value: ${{ steps.set-tflint-vars.outputs.arg }}

runs:
  using: composite
  steps:
    - name: techjavelin/iac-action-terraform-lint // setup lint
      uses: terraform-linters/setup-tflint@v2
      with:
        tflint_version: ${{ inputs.version }}

    - name: techjavelin/iac-action-terraform-lint // initialize
      run: tflint --init
      working-directory: ${{ inputs.source-dir }}
      shell: bash

    - id: set-tflint-vars
      run: |
        if [[ "${{ inputs.vars }}" != "" ]]; then
          VARS=${{ inputs.vars }}
          ARGS=
          for var in ${VARS//,/ }
          do
            ARGS="$ARGS --var='$var'"
          done
          echo "Arguments: $ARGS"
          echo "args=$ARGS" >> $GITHUB_OUTPUT
        else
          echo "args=" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - id: set-tflint-format
      run: |
        if [[ "${{ inputs.format }}" != "" ]]; then
          echo "arg=-f ${{ inputs.format }}" >> $GITHUB_OUTPUT
        else
          echo "arg=" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - id: set-tflint-config
      run: |
        if [[ "${{ inputs.config }}" != "" ]]; then
          echo "arg=--config ${{ inputs.config }}" >> $GITHUB_OUTPUT
        else
          echo "arg=" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: techjavelin/iac-action-terraform-lint // lint
      run: tflint ${{ steps.set-tflint-vars.outputs.arg }} ${{ steps.set-tflint-format.outputs.arg }} ${{ steps.set-tflint-config.outputs.arg }} ${{ inputs.terraform-dir }}
      shell: bash

    
