name: 'techjavelin/iac-github-actions // terraform // lint'
description: 'Lints your terraform files using tflint'

inputs:
  terraform-dir:
    description: "Absolute path or relative path from project root to where your terraform files are"
    default: '.'
    required: false

  tflint-version:
    description: Use a specific version of tflint
    default: latest
    required: false

runs:
  using: composite
  steps:
    - name: techjavelin/iac-action-terraform-lint // setup lint
      uses: terraform-linters/setup-tflint@v2
      with:
        tflint_version: ${{ inputs.tflint-version }}

    - name: techjavelin/iac-action-terraform-lint // initialize
      run: tflint --init
      working-directory: ${{ inputs.source-dir }}
      shell: bash

    - name: techjavelin/iac-action-terraform-lint // lint
      run: tflint -f compact .
      working-directory: ${{ inputs.source-dir }}
      shell: bash
