---
name: "techjavelin // iac-ac-action-terraform-lint"

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  test-terraform-versions:
    name: iac-ac-action-terraform-lint // continuous // test-tflint-versions

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['0.24.1', 'latest']

    runs-on: ${{ matrix.os }}

    steps:
      - name: test-terraform-versions // checkout
        uses: actions/checkout@v3

      - name: test-terraform-versions // execute
        uses: ./
        with:
          tflint-version: ${{ matrix.version }}

      - name: test-terraform-versions // collect-results
        id: collect-results
        run: echo version=$(tflint --version | head -n1 | cut -d" " -f3) >> $GITHUB_OUTPUT

      - name: test-terraform-versions // verify-version
        if: ${{ matrix.version != 'latest' }}
        uses: pr-mpt/actions-assert@v4
        with:
          assertion: npm://@assertions/is-equal
          actual   : ${{ steps.collect-results.outputs.version }}
          expected : ${{ matrix.terraform-version }}

      - name: test-terraform-versions // collect-facts
        id: collect-facts
        run: echo version=$(gh release list -R terraform-linters/tflint --exclude-drafts --limit 10 | grep Latest | cut -f1 | cut -dv -f2) >> $GITHUB_OUTPUT
        if: ${{ matrix.version == 'latest' }}

      - name: test-terraform-versions // verify-latest
        if: ${{ matrix.version == 'latest' }}
        uses: pr-mpt/actions-assert@v4
        with:
          assertion: npm://@assertions/is-equal
          actual   : ${{ steps.collect-results.outputs.version }}
          expected : ${{ steps.collect-facts.outputs.version }}